/**
 * On-disk presence for manifest assets — regenerated by `npm run assets:sync-shipped`.
 * @generated — do not edit manually.
 */

/** Whether processed files exist under public/models/ for each manifest id. */
export const ASSET_DISK_SHIPPED: Readonly<Record<string, boolean>> = {
  env_cafe_props: true,
  fps_arms: true,
  interior_basement: true,
  interior_cafe: true,
  interior_corridor: true,
  interior_factory: true,
  interior_forest_clearing: true,
  interior_library: true,
  interior_office: true,
  interior_pier: true,
  interior_rooftop: true,
  interior_room_bedroom: true,
  npc_albert: true,
  npc_boris: true,
  npc_cafe_barista: true,
  npc_grisha: true,
  npc_kira: true,
  npc_maria_ai3dgen: true,
  npc_office_alexander: true,
  npc_office_colleague: true,
  npc_office_dmitry: true,
  npc_tamara: true,
  npc_viktor: true,
  npc_zarema: true,
  player_volodka: true,
  veg_tree_pine: true,
};
